# Generated by Django 5.2.13 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Sales_User', 'Sales User'), ('L2_Approver', 'Level 2 Approver'), ('L3_Approver', 'Level 3 Approver'), ('PC', 'Project Coordinator'), ('PDR', 'Procurement'), ('CDR', 'Costing'), ('Ops_Manager', 'Operations Manager'), ('Finance', 'Finance'), ('Director', 'Director'), ('Admin', 'Admin'), ('Managing_Director', 'Managing Director'), ('Director_African_Entities', 'Director African Entities and Special Projects'), ('Ops_Project_Manager', 'Operations Project Manager'), ('Ops_Project_Supervisor', 'Operations Project Supervisor'), ('Commercial_Director', 'Commercial Director'), ('Assistant_Commercial_Marketing', 'Assistant to Commercial Director and Marketing Manager'), ('BD_Manager', 'Business Development Manager'), ('BD_Assistant', 'Business Development Assistant')], default='Sales_User', max_length=50),
        ),
    ]
