# Generated by Django 5.2.13 on 2026-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='functional_role',
            field=models.CharField(choices=[('Sales_User', 'Sales User'), ('L2_Approver', 'Level 2 Approver'), ('L3_Approver', 'Level 3 Approver'), ('PC', 'Project Coordinator'), ('PDR', 'Procurement'), ('CDR', 'Costing'), ('Ops_Manager', 'Operations Manager'), ('Finance', 'Finance'), ('Director', 'Director'), ('Admin', 'Admin')], default='Sales_User', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Actual SharePoint job title', max_length=100),
        ),
    ]
