# Generated by Django 5.2.13 on 2026-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role_user_functional_role_user_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='functional_role',
        ),
        migrations.AddField(
            model_name='user',
            name='approval_level',
            field=models.CharField(choices=[('None', 'Not an Approver'), ('L2', 'Level 2 Approver'), ('L3', 'Level 3 Approver')], default='None', help_text='Approval level for TRF workflow', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('Sales', 'Sales User'), ('PC', 'Project Coordinator'), ('PDR', 'Procurement'), ('CDR', 'Costing'), ('Ops', 'Operations'), ('Finance', 'Finance'), ('Director', 'Director'), ('Admin', 'Admin')], default='Sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='SharePoint job title', max_length=100),
        ),
    ]
