# Generated by Django 5.2.13 on 2026-05-04 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_audit_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('CDR_Approved', 'CDR Approved'), ('CDR_Rejected', 'CDR Rejected'), ('Negotiating', 'Negotiating'), ('Submitted_For_Director', 'Submitted for Director'), ('Director_Approved', 'Director Approved'), ('Director_Rejected', 'Director Rejected')], default='Draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costing_sheets_as_cdr', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costing_sheets_as_director', to=settings.AUTH_USER_MODEL)),
                ('pdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costing_sheets_as_pdr', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='costing_sheet', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostingSheetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('provider_1_name', models.CharField(blank=True, max_length=255)),
                ('provider_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_1_currency', models.CharField(blank=True, max_length=3)),
                ('provider_2_name', models.CharField(blank=True, max_length=255)),
                ('provider_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_2_currency', models.CharField(blank=True, max_length=3)),
                ('provider_3_name', models.CharField(blank=True, max_length=255)),
                ('provider_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('provider_3_currency', models.CharField(blank=True, max_length=3)),
                ('selected_provider', models.IntegerField(blank=True, choices=[(1, 'Provider 1'), (2, 'Provider 2'), (3, 'Provider 3')], null=True)),
                ('original_approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('original_approved_currency', models.CharField(blank=True, max_length=3)),
                ('negotiated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('negotiated_currency', models.CharField(blank=True, max_length=3)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.costingsheet')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_line_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['saved_at'],
            },
        ),
        migrations.CreateModel(
            name='POYearCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('prefix', models.CharField(default='PO', max_length=10)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CS_CREATED', 'CS Created'), ('CS_SUBMITTED', 'CS Submitted'), ('CS_CDR_APPROVED', 'CDR Approved'), ('CS_CDR_REJECTED', 'CDR Rejected'), ('CS_NEGOTIATION_STARTED', 'Negotiation Started'), ('CS_QUOTE_REVISED', 'Quote Revised'), ('CS_SUBMITTED_DIRECTOR', 'Submitted to Director'), ('CS_DIRECTOR_APPROVED', 'Director Approved'), ('CS_DIRECTOR_REJECTED', 'Director Rejected'), ('CS_REMEDIATED', 'CS Remediated'), ('LI_CREATED', 'Line Item Created'), ('LI_UPDATED', 'Line Item Updated'), ('LI_DELETED', 'Line Item Deleted'), ('PO_GENERATED', 'PO Generated'), ('PO_ISSUED', 'PO Issued'), ('PO_FULFILLED', 'PO Fulfilled'), ('PO_CANCELLED', 'PO Cancelled'), ('ETA_RECORDED', 'ETA Recorded'), ('ETA_UPDATED', 'ETA Updated'), ('DELIVERY_RECORDED', 'Delivery Recorded'), ('CLIENT_NOTIFIED', 'Client Notified')], max_length=50)),
                ('detail', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='procurement.costingsheet')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Draft', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.costingsheet')),
                ('pdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_pdr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_delivery_date', models.DateField()),
                ('supplier_eta', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('notify_client_required', models.BooleanField(default=False)),
                ('client_notified_at', models.DateTimeField(blank=True, null=True)),
                ('client_notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_notifications', to=settings.AUTH_USER_MODEL)),
                ('costing_sheet_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='procurement.costingsheetlineitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['expected_delivery_date'],
            },
        ),
    ]
