# Generated by Django 4.2.30 on 2026-06-24 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trf', '0003_audit_event_immutability_trigger'),
        ('projects', '0002_project_audit_trigger'),
        ('procurement', '0003_deliverydocument_proofofdelivery_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_type', models.CharField(choices=[('INTERNAL', 'Internal Expense'), ('CLIENT', 'Client Billable'), ('SUPPLIER', 'Supplier Payment')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('L2_APPROVED', 'Level 2 Approved'), ('L3_APPROVED', 'Level 3 Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('description', models.TextField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/%d/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_approvals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('trf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trf.trfrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='procurement.paymentrequisition')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequisitionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(2, 'Level 2'), (3, 'Level 3')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.paymentrequisition')),
            ],
            options={
                'unique_together': {('payment_requisition', 'approver', 'level')},
            },
        ),
    ]
